changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bug fixes 🐛
      labels:
        - fix
        - bug
    - title: Other Changes
      labels:
        - "*"
